server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${db_host}/${db_name}
    username: ${db_username}
    password: ${db_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: "/"